apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  mysql_pass: 'Redhat@123'
  mysql_user: 'root'
  mysql_host: '192.168.0.11'
  mysql_data: '/var/lib/mysql'

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: my-cm