apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp
            port:
              number: 80

      - path: /mobile
        pathType: Prefix
        backend:
          service:
            name: cbzapp
            port:
              number: 80

      - path: /laptop
        pathType: Prefix
        backend:
          service:
            name: mylaptop
            port:
              number: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: cbzapp
  labels:
    app: cbzapp
spec:
  containers:
  - name: cbzapp
    image: shubhamkalsait1/myhttpd:latest
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cbzapp
spec:
  selector:
    app: cbzapp
  ports:
  - port: 80
    targetPort: 80


---
apiVersion: v1
kind: Pod
metadata:
  name: mylaptop
  labels:
    app: mylaptop
spec:
  containers:
  - name: mylaptop
    image: nginx
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mylaptop
spec:
  selector:
    app: mylaptop
  ports:
  - port: 80
    targetPort: 80