apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  my_pass: 'Q2xvdWRibGl0ekAxMjM='
  my_user: 'c2h1YmhhbQ=='

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: my_user 


